// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SmartHostelManagementSystem.Data;

#nullable disable

namespace SmartHostelManagementSystem.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20251010074627_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.9");

            modelBuilder.Entity("SmartHostelManagementSystem.Models.Complaint", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("StudentId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("StudentId");

                    b.ToTable("Complaints");
                });

            modelBuilder.Entity("SmartHostelManagementSystem.Models.MessMenu", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Breakfast")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("DayOfWeek")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Dinner")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Lunch")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("MessMenus");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Breakfast = "Poha",
                            DayOfWeek = 1,
                            Dinner = "Khadhi, Khichdi",
                            Lunch = "Roti, Sabji, Dal"
                        },
                        new
                        {
                            Id = 2,
                            Breakfast = "Upma",
                            DayOfWeek = 2,
                            Dinner = "Rice, Dal Fry",
                            Lunch = "Roti, Paneer"
                        },
                        new
                        {
                            Id = 3,
                            Breakfast = "Idli Sambhar",
                            DayOfWeek = 3,
                            Dinner = "Veg Biryani",
                            Lunch = "Puri, Chole"
                        });
                });

            modelBuilder.Entity("SmartHostelManagementSystem.Models.Room", b =>
                {
                    b.Property<int>("RoomNo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("Capacity")
                        .HasColumnType("INTEGER");

                    b.Property<int>("OccupiedCount")
                        .HasColumnType("INTEGER");

                    b.HasKey("RoomNo");

                    b.ToTable("Rooms");

                    b.HasData(
                        new
                        {
                            RoomNo = 101,
                            Capacity = 2,
                            OccupiedCount = 2
                        },
                        new
                        {
                            RoomNo = 102,
                            Capacity = 3,
                            OccupiedCount = 1
                        });
                });

            modelBuilder.Entity("SmartHostelManagementSystem.Models.Student", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsAdmin")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("RoomNo")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("Students");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Email = "admin@hostel.com",
                            IsAdmin = true,
                            Name = "Ansh Desai",
                            Password = "admin",
                            RoomNo = 101
                        },
                        new
                        {
                            Id = 2,
                            Email = "john@student.com",
                            IsAdmin = false,
                            Name = "John Doe",
                            Password = "password",
                            RoomNo = 102
                        });
                });

            modelBuilder.Entity("SmartHostelManagementSystem.Models.Complaint", b =>
                {
                    b.HasOne("SmartHostelManagementSystem.Models.Student", "Student")
                        .WithMany()
                        .HasForeignKey("StudentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Student");
                });
#pragma warning restore 612, 618
        }
    }
}
